### ISSUE TITLE
Prism !

### ISSUE THREAD

**Issue by Shaenn** [jebissey/hello-word#2]
Hop, jai vu que tu as star mon projet template, et tu as l'air de t'intéresser à cette technologie. Malheureusement il est utilisable qu'en interne dans mon entreprise ;-) je peux néanmoins te fournir un projet neutre complet généré avec. L' architecture Prism mise en oeuvre est le résultat de quelques années de recherche pour tout bien faire ! C'est tellement vaste et intéressant comme techno !
Bien à toi,

Shaenn

**Comment by jebissey** [comment]
Bonjour Shaenn
Merci pour ton message.
Effectivement je m'intéresse à Prism, et je serais vraiment ravi que tu puisses me fournir ton projet neutre.
Bien cordialement
